config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "pages#home"

  resources :clients, only: %i(index show new create edit update)
  resources :bookings
  resources :categories, only: %i(index new create edit update destroy) do
    resources :sub_categories, only: %i(index new create edit update destroy)
  end

  resources :plannings, only: %i(index new create) do
    resources :shifts, only: %i(new create)
  end
  get "planning(/:id)", to: "plannings#show", as: "planning"

  get 'dashboard', to: 'pages#dashboard'
  post 'getclient', to: 'bookings#getclient'
  post 'getsubcat', to: 'bookings#getsubcat'
end

app/models/booking.rb
class Booking < ApplicationRecord
  extend SimpleCalendar

  attr_accessor :phone_number, :name, :surname, :category

  validates_presence_of :phone_number, :name, :surname, allow_blank: true

  has_many :calendars
  has_many :sales
  has_many :booking_sub_categories
  has_many :sub_categories, through: :booking_sub_categories

  belongs_to :client

  default_scope -> { order(:start_time) }

  validates :start_time, :end_time, :total_price, presence: true
end

app/controllers/bookings_controller.rb
require 'date'

class BookingsController < ApplicationController
  skip_before_action :verify_authenticity_token, only: [:getclient, :getsubcat]

  def index
    start_date = params.fetch(:start_date, Date.today).to_date
    @bookings = Booking.where(start_time: start_date.beginning_of_week..start_date.end_of_week)
  end

  def show
  end

  def new
    @categories = Category.all
    @booking = Booking.new
  end

  def getclient
    phone = params['phone']
    clients = Client.where("phone_number LIKE '%#{phone}%'")
    render json: clients
  end

  def getsubcat
    if params["category"] == ""
      sub_categories = []
    else
      category = Category.find(params["category"].to_i)
      sub_categories = SubCategory.where(category_id: category)
    end
    render json: sub_categories
  end

  def create
    @booking = Booking.new(booking_params)

    sub_categories_ids = params[:booking][:sub_cats].values
    
    price = 0
    total_time = 0

    sub_categories_ids.each do |id|
      sub_cat = SubCategory.find(id.to_i)
      price += sub_cat.price
      total_time += sub_cat.time
    end

    start = DateTime.new(params[:booking]['start_time(1i)'].to_i, 
      params[:booking]['start_time(2i)'].to_i, 
      params[:booking]['start_time(3i)'].to_i, 
      params[:booking]['start_time(4i)'].to_i, 
      params[:booking]['start_time(5i)'].to_i)

    finish = start + total_time.seconds

    client = Client.find_or_create_by(phone_number: params[:booking][:phone_number]) do |client|
      client.name = params[:booking][:name]
      client.surname = params[:booking][:surname]
      client.phone_number = params[:booking][:phone_number]
    end

    @booking.client = client
    @booking.start_time = start
    @booking.end_time = finish
    @booking.total_price = price
    @booking.save!
    
    sub_categories_ids.each_with_index do |id, index|
      booking_sub_cat = BookingSubCategory.new(
        booking: @booking,
        sub_category_id: id.to_i
      )
      if index == sub_categories_ids.count - 1
        if booking_sub_cat.save!
          redirect_to bookings_path
          flash[:success] = "your booking is registered"
        else
          render :new, status: :unprocessable_entity
        end
      else
        booking_sub_cat.save!
      end
    end    
  end

  def edit
  end

  def destroy
  end

  private

  def booking_params
    params.require(:booking).permit(:start_time, :note, :confirmed, :total_price, :end_time)
  end
end

app/views/bookings/_form.html.erb
<div data-controller="client-search">
  <%= simple_form_for @booking, validate: true do |f| %>
    <div data-client-search-target="form">
      <div>
        <%= f.input :phone_number, 
          validate: { uniqueness: true, 
          length: { minimum: 10, too_short: "number too short" }, 
          format: { with: / \d+ /, message: "allow only letter" }}, 
          input_html: { 
            data: { 
              client_search_target: 'phone', 
              action: 'keyup->client-search#search' 
            }
          }, 
          label: "Customer's phone number", 
          style: "display: block" 
        %>
        <p data-client-search-target = "phoneInput"></p>
      </div>
      <div>
        <%= f.input :name, input_html: { data: { client_search_target: 'clientname' }}, label: "Customer's name", style: "display: block" %>
      </div>
      <div>
        <%= f.input :surname, input_html: { data: { client_search_target: 'clientsurname' }}, label: "Customer's surname", style: "display: block" %>
      </div>
      <div>
        <%= f.input :start_time, placeholder: 'start_at' %>
      </div>
      <div data-controller="add-booking-works">
        <div data-add-booking-works-target="bookingWorks">
          <div class="cats" data-client-search-target="catDiv">
            <div>
              <%= f.input :category, collection: Category.order(:name), prompt: "Select a Category", label: false, multiple: true, input_html: { data: { client_search_target: 'category', action: "change->client-search#select" }} %>
            </div>
          </div>
        </div>
        <div>
          <p data-action="click->add-booking-works#addWork">Add another work</p>
        </div>
      </div>
      </div>
      <div>
        <%= f.input :note, label: "Notes", style: "display: block" %>
      </div>
      <div>
        <%= f.submit "Register", data: { client_search_target: 'submit' } %>
      </div>
    </div>
  <% end %>
</div>

app/views/bookings/index.html.erb
<div class="container mt-5 text-center">
  <%= link_to new_booking_path, class: "home-link" do %>
    <button class="home_button reservation_button">
      <div class="grey">
        ΚΑΝΕ ΜΙΑ ΚΡΑΤΗΣΗ
      </div>
    </button>
  <% end %>
  <%= week_calendar(events: @bookings) do |date, bookings| %>
    <div class="day">
      <%= date.strftime("%e %b %Y") %>
    </div>
    <div>
      <% bookings.each do |booking| %>
        <%= booking.client.full_name %>
        <p>from <%= booking.start_time.strftime("%H:%M") %> to <%= booking.end_time.strftime("%H:%M") %></p>
      <% end %>
    </div>
  <% end %>
</div>

app/views/bookings/new.html.erb
<div class="container">
<h1> New Booking </h1>

<%= render "form" %>
<br>
<div>
 <%= link_to "back to timetable", bookings_path %>
</div>
</div>