config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "pages#home"

  resources :clients, only: %i(index show new create edit update)
  resources :bookings
  resources :categories, only: %i(index new create edit update destroy) do
    resources :sub_categories, only: %i(index new create edit update destroy)
  end

  resources :plannings, only: %i(index new create) do
    resources :shifts, only: %i(new create)
  end
  get "planning(/:id)", to: "plannings#show", as: "planning"

  get 'dashboard', to: 'pages#dashboard'
  post 'getclient', to: 'bookings#getclient'
  post 'getsubcat', to: 'bookings#getsubcat'
end

app/models/planning.rb
class Planning < ApplicationRecord
  has_many :shifts
  has_many :employees, through: :shifts

  WEEK_DAYS = %w(Monday Tuesday Wednesday Thursday Friday Saturday Sunday)
end

app/controllers/plannings_controller.rb
class PlanningsController < ApplicationController
  def index
    @plannings = Planning.where(:from == Date.today.year)
  end

  def show
    this_week = Time.now.strftime("%V").to_i

    if params[:id]
      @planning = Planning.find(params[:id])
    else
      @planning = Planning.find_by(week: this_week).nil? ? Planning.last : Planning.find_by(week: this_week)
    end

    @employees = Employee.all
    @shifts = @planning.shifts
    time = Time.new(@planning.from.strftime("%Y"), @planning.from.strftime("%m"), @planning.from.strftime("%d"), 10, 00)
    day = Date.new(@planning.to.strftime("%Y").to_i, @planning.from.strftime("%m").to_i, @planning.from.strftime("%d").to_i)
    
    # @monday_shifts = shifts.filter { |shift| shift.beginning.monday? }
    # @tuesday_shifts = shifts.filter { |shift| shift.beginning.tuesday? }
    # @wednesday_shifts = shifts.filter { |shift| shift.beginning.wednesday? }
    # @thursday_shifts = shifts.filter { |shift| shift.beginning.thursday? }
    # @friday_shifts = shifts.filter { |shift| shift.beginning.friday? }
    # @saturday_shifts = shifts.filter { |shift| shift.beginning.saturday? }
    # @sunday_shifts = shifts.filter { |shift| shift.beginning.sunday? }

    # @week_shifts = []
    # @week_shifts.push(@monday_shifts, @tuesday_shifts, @wednesday_shifts, @thursday_shifts, @friday_shifts, @saturday_shifts)
  end

  def new
    @planning = Planning.new
  end

  def create
    @planning = Planning.new(planning_params)
    ending = params[:planning][:from].to_date.sunday()
    week = ending.strftime("%V").to_i
    @planning.to = ending
    @planning.week = week
    if @planning.save!
      redirect_to planning_path
    else
      render :new, status: :unprocessable_entity
    end
  end

  private

  def planning_params
    params.require(:planning).permit(:week, :from, :to)
  end
end

app/views/plannings/_planning.html.erb
<div class="planning d-flex">
    <div class="planning-hours">
      <div class="hours">Heures</div>
      <div class="hour">9h</div>
      <div class="hour">10h</div>
      <div class="hour">11h</div>
      <div class="hour">12h</div>
      <div class="hour">13h</div>
      <div class="hour">14h</div>
      <div class="hour">15h</div>
      <div class="hour">16h</div>
      <div class="hour">17h</div>
      <div class="hour">18h</div>
      <div class="hour">19h</div>
      <div class="hour">20h</div>
      <div class="hour">21h</div>
    </div>

    <div id="planning-table" data-controller="planning" data-planning-shifts-value="<%= @shifts %>">

      <% Tonic::TONIC_ATHENS_DAYS.each do |day| %>
        <div class="<%= day[:name] %> day-column">
          <div class="day-cell"><%= day[:name] %></div>


          <%# debut d'idée pour créer la grille %>

          <%# <div>
            <div class="table-line"></div>
          </div> %>


          <% shifts = @shifts.select{ |shift| shift.beginning.strftime("%A") == day[:name] } %>
          <% unless shifts.empty? %>
            <div class="shift-cell">
              <% shifts.each do |shift| %>
                <% start_index = (shift.beginning - (9 * 3600)).strftime("%H").to_f.floor * 6 %>
                <% end_index = (shift.ending - (9 * 3600)).strftime("%H").to_f.floor * 6 - 1 %>
                <div class="shift-column">
                  <div class="shift-perso" style="height:<%= 5 * start_index %>px;"><span><%= (5 * start_index) > 0 ? "-" : "" %></span></div>
                  <div class="shift-perso" style="height:<%= 5 * (end_index - start_index) %>px; background-color: <%= shift.employee.color %>;">
                    <span><%= shift.employee.first_name %></span>
                    <span><%= shift.beginning.strftime("%H:%M") %></span>
                    <span>-</span>
                    <span><%= shift.ending.strftime("%H:%M") %></span>
                    
                    </div>
                  <div class="shift-perso" style="height:<%= 5 * (78 - end_index) %>px;"><%= (5 * (78 - end_index)) < 10 ? "" : "-" %></div>
                </div>
              <% end %>
            </div>
          <% end %>
        </div>
      <% end %>
    </div>
</div>

app/views/plannings/index.html.erb
<div>
  <h1>Plannings of <%= Date.today.year %></h1>
</div>

<div>
  <%= link_to "Create a new planning", new_planning_path %>
</div>

<div>
  <ul>
    <% @plannings.each do |planning| %>
      <li>
        <%= link_to planning_path(planning) do %>
          Planning from <%= planning.from.strftime("%d %B %Y") %> to <%= planning.to.strftime("%d %B %Y") %> (week <%= planning.week %>)
        <% end %>
      </li>
    <% end %>
  </ul>
</div>

app/views/plannings/new.html.erb
<div>
  <h1>New planning</h1>
</div>
<div data-controller="new-planning">
  <%= form_with model: @planning do |form| %>
    <%= form.label :from, "week starting on :" %>
    <%= form.date_field :from, data: { new_planning_target: "from", action: "change->new-planning#checkMonday" } %>
    <%= form.submit data: { new_planning_target: "submit" } %>
  <% end %>
  <p data-new-planning-target="error"></p>
</div>

app/views/plannings/show.html.erb
<div class="container">
  <h1>Planning Week <%= @planning.week %></h1>
  <div class="display-col">
    <%= link_to "all plannings", plannings_path %>
    <%= link_to "Add a shift", new_planning_shift_path(@planning) %>
  </div>
  <%= render "planning" %>
</div>